spring.application.name=itws-2026-final-project
spring.datasource.url=jdbc:mysql://localhost:3309/itws_2026_final_project_db
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=root
server.port=7000